## Biblioteca Numpy

Numpy é uma biblioteca utilizada, principalmente, para realizae cálculos com matrizes (Arrays Multidimensionais). Ela fornece diversas funções que facilitam diversos cálculos numéricos muito utilizados em Data Science e também na Engenharia.

Para instalar a biblioteca Numpy, é necessário realizar um "pip". </br>

<i> pip install numpy</i>
</br>

#### Ou se estiver utilizando o Anaconda, o Numpy já está instalado
</br></br>
Outra grande importância da biblioteca Numpy é que ela é base para diversas outras bibliotecas (inclusive iremos utilizar aqui). Citando algumas: MatplotLib, Pandas...

<b>Mais informações e tutoriais:</b> <a href=https://www.numpy.org/>Aqui</a>

In [1]:
import numpy as np #np é a abreviação mais utilizada para numpy

In [2]:
matriz=np.array([1,2,3])

In [3]:
matriz

array([1, 2, 3])

In [4]:
print(matriz)

[1 2 3]


In [6]:
type(matriz)

numpy.ndarray

#### Os tipos de dados no Numpy

Os tipos de dados variam entre <b>int </b> e <b>float</b>

In [7]:
x=np.array([1,2])
x.dtype

dtype('int32')

In [8]:
y=np.array([1.1,2.2])
y.dtype

dtype('float64')

### Apresentando algumas funções presentes no Numpy

#### Vetor de 5 elementos no intervalo de 1 a 5

In [13]:
print(np.linspace(1,5,5))

[1. 2. 3. 4. 5.]


#### Vetor de 5 elementos em um intervalo de 5 elementos

In [15]:
print(np.arange(5))

[0 1 2 3 4]


#### Vetor nulo de 5 elementos

In [16]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


#### Matriz nula (3,3)

In [21]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Matriz  (3,3) de 1

In [23]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### Matriz identidade (3,3)

In [24]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Matrizes de números aleatórios 

Em vários exemplos pela internet vocês se deparão com a criação de matrizes, vetores, com números aleatórios. Essa função é realizada através do numpy:

In [31]:
aleatorio=np.random.random((3,3)) ##random.random = numeros aleatorios entre 0  1

In [32]:
aleatorio

array([[0.72076624, 0.69401134, 0.95923546],
       [0.3338171 , 0.79908237, 0.20293777],
       [0.35049543, 0.97462037, 0.20846385]])

In [48]:
aleatorio2=np.random.sample(5)

In [49]:
aleatorio2 #entre 0 e 1 também

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

### Algumas funções matemáticas

In [52]:
media=np.mean(aleatorio2) #Média
print(media)

0.664471720887647


In [71]:
desvio_padrao=np.std(aleatorio2)
print(desvio_padrao)

0.23322985774451155


In [72]:
minimo=np.amin(a) #minimo
print(minimo)

1


In [73]:
maximo=np.amax(a) #maximo
print(maximo)

4


In [85]:
d=np.array([1,2,6,3,2,4,6,7,1,3,4,6,8,8,8,2])
hist=np.histogram(d) #montando um histograma
print(hist)#mostra a contagem e os intervalos

(array([2, 3, 2, 0, 2, 0, 0, 3, 1, 3], dtype=int64), array([1. , 1.7, 2.4, 3.1, 3.8, 4.5, 5.2, 5.9, 6.6, 7.3, 8. ]))


### Alguns cálculos com matrizes

In [57]:
a=np.array([[1,2],[3,4]])
b=np.array([[3,4],[1,2]])

In [58]:
a

array([[1, 2],
       [3, 4]])

In [59]:
b

array([[3, 4],
       [1, 2]])

In [60]:
print(np.add(a,b)) #soma

[[4 6]
 [4 6]]


In [61]:
print(np.subtract(a,b)) #subtração

[[-2 -2]
 [ 2  2]]


In [62]:
print(np.multiply(a,b)) #multiplicação

[[3 8]
 [3 8]]


In [63]:
print(np.divide(a,b)) #divisão

[[0 0]
 [3 2]]


In [64]:
print(np.sqrt(a)) # raiz quadrada

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [67]:
print(a.dot(b)) #produto entre matrizes

[[ 5  8]
 [13 20]]


In [68]:
print(np.sum(a)) #soma dos elementos das matrizes

10


In [70]:
print(np.sum(a,axis=0)) #soma dos elementos das colunas x

[4 6]
